### ISSUE TITLE
Compliance reports 100% if no checks are run

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#24] opened 2016-04-15 17:46 UTC
When running a suite of checks against distributions that are not supported in the `data` fields, compliance reports 100%.

0 tests run. 0 tests failed / passed. 100% compliant?

**Comment by basepi** [comment] 2016-04-15 17:50
Uh, that's weird. It shouldn't, that should get caught by https://github.com/HubbleStack/Nova/blob/7affdbdae966d9165cd631f1df741fc5791743ec/_modules/nova.py#L103

I'll have to test this, I guess.

**Comment by cedwards** [comment] 2016-04-15 18:25
```
saturn ~ # salt \* nova.audit show_success=False
saturn.corp.adobe.com:
    ----------
    Compliance:
        100%
    Failure:
arch04:
    ----------
    Compliance:
        100%
    Failure:
arch03:
    ----------
    Compliance:
        100%
    Failure:
arch01:
    ----------
    Compliance:
        100%
    Failure:
arch02:
    ----------
    Compliance:
        100%
    Failure:
arch05:
    ----------
    Compliance:
        100%
    Failure:
```

**Comment by basepi** [comment] 2016-04-15 18:34
The weirdness in the output is because the successes were hidden. Closing as expected behavior.

**Closed as completed by basepi** 2016-04-15 18:34 UTC
Labels: Bug
