### ISSUE TITLE
Doc Issue?

### ISSUE THREAD

**Issue by rterbush** [HubbleStack/Nova#41] opened 2016-04-22 21:43 UTC
Excited to help out with this project, but needing a bit of clarity to get started.

Following the docs to get setup, when calling <code>nova.audit</code> (or other nova commands), I get the following:

```
[root@master /usr/local/etc/salt/formulas]# salt \* nova.audit
minion1:
    'nova' __virtual__ returned False
```

If I use instead <code>hubble.audit</code> (or .sync, etc) I start seeing some expected behavior:

```
[root@master /usr/local/etc/salt/formulas]# salt \* hubble.audit
minion1:
    ----------
    Failure:
    Success:
```

Docs refer to using <code>tags=</code> but appears that it is <code>tag=</code> in the code.

I also see a reference to a directory layout that does not seem to be supported in the current code:
https://hubblestack.readthedocs.org/en/latest/chapters/hubble.html

Happy to help with changes if you can point me in the right direction.

**Comment by basepi** [comment] 2016-04-22 21:57
We renamed nova.py to hubble.py to avoid clashing with the openstack nova module built in to salt. Still need to update some of the references in the readme and the like.

Also, thanks for pointing out the tag vs tags issue, we'll get that sorted.

**Comment by dgmorrisjr** [comment] 2016-04-23 00:21
I am also excited about hubblestack and really enjoyed the presentation/demo at SaltConf16, looking forward to using this in our environments.  Same issue mentioned by @rterbush above.  if we run hubble.audit with no arguments, I guess i was expecting to see the audit performed against the full contents in the CIS.yaml file (from the salt://hubblestack_nova directory).   Am I mis-understanding how to use the tool?   I was receiving the same output above, then once I got the hubblestack_nova directory setup properly, i starting receiving the following ouput:

```
[root@master ~]# salt \* hubble.audit
minion1:
    ----------
    Failure:
minion2:
    ----------
    Failure:
```

**Comment by gmiu** [comment] 2016-04-23 00:41
What OS is running on your minions?

**Comment by gmiu** [comment] 2016-04-23 00:50
So yes, I know what the problem is. The `CIS.yaml` only supports CentOS 7 at the moment. We'll update the test suite in the next period of time (for CentOS 6 in a couple of days or so). My guess is your not using CentOS 6 either (we have just two tests for this one also).

**Comment by gmiu** [comment] 2016-04-23 01:49
The doc issue is fixed in #43. 

#42 was created in order to support CentOS 6.

**Closed as completed by gmiu** 2016-04-23 01:49 UTC
Labels: Bug

**Comment by dgmorrisjr** [comment] 2016-04-23 02:05
RHEL 6.6 is the OS.

**Comment by gmiu** [comment] 2016-04-23 02:17
So, the `CIS.yaml` has the following structure:

```
pkg:
  blacklist:

    telnet:
      data:
        'CentOS Linux-7':
          - 'telnet-server': 'CIS-2.1.1'
          - 'telnet': 'CIS-2.1.2'
      description: 'Remove telnet and telnet-server (Scored)'
      alert: email
      trigger: state
```

See the `'CentOS Linux-7'` key there: it's the exact string returned by `__grains__.get('osfinger')`.
If, for a test, that string does not match the OS your minion is running, it won't run the test.
